Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,7 +17,7 @@ jobs:
       run: |
           echo "Repository: $GITHUB_REPOSITORY"
           echo "TOKEN: ${{ secrets.GITHUB_TOKEN }}"
-          echo "something27"
+          echo "something63"
           echo "SHA: $GITHUB_SHA"
 
 
@@ -31,10 +31,10 @@ jobs:
           echo "contractAddress=$(jq -r '.contractAddress' config.json)" >> $GITHUB_ENV
 
 
-    - name: Use the JSON values
-      run: |
-          echo "Using vmType: $vmType"
-          echo "Using contractAddress: $contractAddress"
+    # - name: Use the JSON values
+    #   run: |
+    #       echo "Using vmType: $vmType"
+    #       echo "Using contractAddress: $contractAddress"
 
 
     - name: Set up JDK 17
@@ -51,54 +51,54 @@ jobs:
         echo "After chmod on wrapper"
 
 
-    - name: Download dependencies
-      run: |
-        echo "Dowloading the dependencies...."
-        ./gradlew --no-daemon --quiet dependencies
-        echo "Dependencies downloaded."
+    # - name: Download dependencies
+    #   run: |
+    #     echo "Dowloading the dependencies...."
+    #     ./gradlew --no-daemon --quiet dependencies
+    #     echo "Dependencies downloaded."
 
 
-    - name: Fetch and build dependency hash map in JSON format
-      run: |
-        echo "Downloaded dependencies and their hashes:"
-        files=$(find ~/.gradle/caches/modules-2/files-2.1 -type f -name '*.jar')
-        echo "{" > deps_hashes.json
-        echo -e "\t\"contractAddress\": \"${contractAddress}\"," >> deps_hashes.json
-        echo -e "\t\"depsHashesMap\": {" >> deps_hashes.json
-        for file in $files; do
-          hash=$(sha256sum "$file" | cut -d " " -f1)
-          filename=$(basename "$file")
-          echo -e "\t\t\"$filename\": \"$hash\"," >> deps_hashes.json
-        done
-        # Remove the last comma and close the JSON array
-        sed -i '$ s/,$//' deps_hashes.json
-        echo -e "\t}" >> deps_hashes.json
-        echo "}" >> deps_hashes.json
+    # - name: Fetch and build dependency hash map in JSON format
+    #   run: |
+    #     echo "Downloaded dependencies and their hashes:"
+    #     files=$(find ~/.gradle/caches/modules-2/files-2.1 -type f -name '*.jar')
+    #     echo "{" > deps_hashes.json
+    #     echo -e "\t\"contractAddress\": \"${contractAddress}\"," >> deps_hashes.json
+    #     echo -e "\t\"depsHashesMap\": {" >> deps_hashes.json
+    #     for file in $files; do
+    #       hash=$(sha256sum "$file" | cut -d " " -f1)
+    #       filename=$(basename "$file")
+    #       echo -e "\t\t\"$filename\": \"$hash\"," >> deps_hashes.json
+    #     done
+    #     # Remove the last comma and close the JSON array
+    #     sed -i '$ s/,$//' deps_hashes.json
+    #     echo -e "\t}" >> deps_hashes.json
+    #     echo "}" >> deps_hashes.json
 
 
-    - name: Print contents of dependency hash map 
-      run: |
-        cat deps_hashes.json
+    # - name: Print contents of dependency hash map 
+    #   run: |
+    #     cat deps_hashes.json
 
 
-    - name: Make HTTP GET request with curl - to esm, for dependency check
-      run: |
-          echo 'starting curl'
-          BASE_URL="https://5045-86-127-179-145.ngrok-free.app/blockchain/dependency-check"
-          PARAMS=""
+    # - name: Make HTTP GET request with curl - to esm, for dependency check
+    #   run: |
+    #       echo 'starting curl'
+    #       BASE_URL="https://2b9c96b1370aa52a594af09b1132090a.serveo.net/blockchain/dependency-check"
+    #       PARAMS=""
 
-          echo 'before actual curl'
-          RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X POST -H "Content-Type: application/json" -d @deps_hashes.json "${BASE_URL}${PARAMS}")
-          echo 'after actual curl'
+    #       echo 'before actual curl'
+    #       RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X POST -H "Content-Type: application/json" -d @deps_hashes.json "${BASE_URL}${PARAMS}")
+    #       echo 'after actual curl'
 
 
-          if [[ ${RESPONSE} -ge 400 ]]; then
-            echo "HTTP error occurred: ${RESPONSE}"
-            cat response.json
-            exit 1  # Exit with a non-zero status to fail the CI/CD pipeline
-          fi
+    #       if [[ ${RESPONSE} -ge 400 ]]; then
+    #         echo "HTTP error occurred: ${RESPONSE}"
+    #         cat response.json
+    #         exit 1  # Exit with a non-zero status to fail the CI/CD pipeline
+    #       fi
 
-          echo "Success: ${RESPONSE}"
+    #       echo "Success: ${RESPONSE}"
 
 
     - name: Build with Gradle
@@ -108,17 +108,17 @@ jobs:
         echo "Build process completed."
 
 
-    - name: Test with Gradle
-      run: |
-        echo "Starting the testing process"
-        ./gradlew test
-        echo "Testing process done."
+    # - name: Test with Gradle
+    #   run: |
+    #     echo "Starting the testing process"
+    #     ./gradlew test
+    #     echo "Testing process done."
 
 
     - name: Make HTTP GET request with curl - to esm, for deployment
       run: |
           echo 'entered depeloy step' 
-          BASE_URL="https://5045-86-127-179-145.ngrok-free.app/deploy"
+          BASE_URL="https://2b9c96b1370aa52a594af09b1132090a.serveo.net/deploy"
           PARAMS="?vmType=$vmType&repoUrl=https://github.com/$GITHUB_REPOSITORY.git&lastCommitHash=$GITHUB_SHA"
 
           echo 'right before curl'
