Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,24 +17,24 @@ jobs:
       run: |
           echo "Repository: $GITHUB_REPOSITORY"
           echo "TOKEN: ${{ secrets.GITHUB_TOKEN }}"
-          echo "something22"
+          echo "something25"
           echo "SHA: $GITHUB_SHA"
 
 
-    # - name: Install jq
-    #   run: sudo apt-get update && sudo apt-get install -y jq
+    - name: Install jq
+      run: sudo apt-get update && sudo apt-get install -y jq
 
 
-    # - name: Extract values from JSON
-    #   run: |
-    #       echo "vmType=$(jq -r '.vmType' config.json)" >> $GITHUB_ENV
-    #       echo "contractAddress=$(jq -r '.contractAddress' config.json)" >> $GITHUB_ENV
+    - name: Extract values from JSON
+      run: |
+          echo "vmType=$(jq -r '.vmType' config.json)" >> $GITHUB_ENV
+          echo "contractAddress=$(jq -r '.contractAddress' config.json)" >> $GITHUB_ENV
 
 
-    # - name: Use the JSON values
-    #   run: |
-    #       echo "Using vmType: $vmType"
-    #       echo "Using contractAddress: $contractAddress"
+    - name: Use the JSON values
+      run: |
+          echo "Using vmType: $vmType"
+          echo "Using contractAddress: $contractAddress"
 
 
     - name: Set up JDK 17
@@ -51,54 +51,54 @@ jobs:
         echo "After chmod on wrapper"
 
 
-    # - name: Download dependencies
-    #   run: |
-    #     echo "Dowloading the dependencies...."
-    #     ./gradlew --no-daemon --quiet dependencies
-    #     echo "Dependencies downloaded."
+    - name: Download dependencies
+      run: |
+        echo "Dowloading the dependencies...."
+        ./gradlew --no-daemon --quiet dependencies
+        echo "Dependencies downloaded."
 
 
-    # - name: Fetch and build dependency hash map in JSON format
-    #   run: |
-    #     echo "Downloaded dependencies and their hashes:"
-    #     files=$(find ~/.gradle/caches/modules-2/files-2.1 -type f -name '*.jar')
-    #     echo "{" > deps_hashes.json
-    #     echo -e "\t\"contractAddress\": \"${contractAddress}\"," >> deps_hashes.json
-    #     echo -e "\t\"depsHashesMap\": {" >> deps_hashes.json
-    #     for file in $files; do
-    #       hash=$(sha256sum "$file" | cut -d " " -f1)
-    #       filename=$(basename "$file")
-    #       echo -e "\t\t\"$filename\": \"$hash\"," >> deps_hashes.json
-    #     done
-    #     # Remove the last comma and close the JSON array
-    #     sed -i '$ s/,$//' deps_hashes.json
-    #     echo -e "\t}" >> deps_hashes.json
-    #     echo "}" >> deps_hashes.json
+    - name: Fetch and build dependency hash map in JSON format
+      run: |
+        echo "Downloaded dependencies and their hashes:"
+        files=$(find ~/.gradle/caches/modules-2/files-2.1 -type f -name '*.jar')
+        echo "{" > deps_hashes.json
+        echo -e "\t\"contractAddress\": \"${contractAddress}\"," >> deps_hashes.json
+        echo -e "\t\"depsHashesMap\": {" >> deps_hashes.json
+        for file in $files; do
+          hash=$(sha256sum "$file" | cut -d " " -f1)
+          filename=$(basename "$file")
+          echo -e "\t\t\"$filename\": \"$hash\"," >> deps_hashes.json
+        done
+        # Remove the last comma and close the JSON array
+        sed -i '$ s/,$//' deps_hashes.json
+        echo -e "\t}" >> deps_hashes.json
+        echo "}" >> deps_hashes.json
 
 
-    # - name: Print contents of dependency hash map 
-    #   run: |
-    #     cat deps_hashes.json
+    - name: Print contents of dependency hash map 
+      run: |
+        cat deps_hashes.json
 
 
-    # - name: Make HTTP GET request with curl - to esm, for dependency check
-    #   run: |
-    #       echo 'starting curl'
-    #       BASE_URL="https://5045-86-127-179-145.ngrok-free.app/blockchain/dependency-check"
-    #       PARAMS=""
+    - name: Make HTTP GET request with curl - to esm, for dependency check
+      run: |
+          echo 'starting curl'
+          BASE_URL="https://5045-86-127-179-145.ngrok-free.app/blockchain/dependency-check"
+          PARAMS=""
 
-    #       echo 'before actual curl'
-    #       RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X POST -H "Content-Type: application/json" -d @deps_hashes.json "${BASE_URL}${PARAMS}")
-    #       echo 'after actual curl'
+          echo 'before actual curl'
+          RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X POST -H "Content-Type: application/json" -d @deps_hashes.json "${BASE_URL}${PARAMS}")
+          echo 'after actual curl'
 
 
-    #       if [[ ${RESPONSE} -ge 400 ]]; then
-    #         echo "HTTP error occurred: ${RESPONSE}"
-    #         cat response.json
-    #         exit 1  # Exit with a non-zero status to fail the CI/CD pipeline
-    #       fi
+          if [[ ${RESPONSE} -ge 400 ]]; then
+            echo "HTTP error occurred: ${RESPONSE}"
+            cat response.json
+            exit 1  # Exit with a non-zero status to fail the CI/CD pipeline
+          fi
 
-    #       echo "Success: ${RESPONSE}"
+          echo "Success: ${RESPONSE}"
 
 
     - name: Build with Gradle
@@ -107,44 +107,28 @@ jobs:
         ./gradlew build -x test
         echo "Build process completed."
 
-    - name: Print JAR size
+
+    - name: Test with Gradle
       run: |
-        echo "Listing JAR content:"
-        ls -lh build/libs/
-        echo "Displaying file size of the JAR:"
-        jar_file=$(ls build/libs/*-SNAPSHOT.jar)
-        du -h "$jar_file"
+        echo "Starting the testing process"
+        ./gradlew test
+        echo "Testing process done."
 
 
-    - name: List contents of the JAR file
+    - name: Make HTTP GET request with curl - to esm, for deployment
       run: |
-        echo "Listing contents of the JAR file:"
-        jar_file=$(ls build/libs/*-SNAPSHOT.jar)
-        xxd "$jar_file"
+          echo 'entered depeloy step' 
+          BASE_URL="https://5045-86-127-179-145.ngrok-free.app/deploy"
+          PARAMS="?vmType=$vmType&repoUrl=https://github.com/$GITHUB_REPOSITORY.git&lastCommitHash=$GITHUB_SHA"
 
+          echo 'right before curl'
+          RESPONSE=$(curl -s -o response.json -w "%{http_code}" "${BASE_URL}${PARAMS}")
+          echo 'right after curl'
 
+          if [[ ${RESPONSE} -ge 400 ]]; then
+            echo "HTTP error occurred: ${RESPONSE}"
+            cat response.json
+            exit 1  # Exit with a non-zero status to fail the CI/CD pipeline
+          fi
 
-    # - name: Test with Gradle
-    #   run: |
-    #     echo "Starting the testing process"
-    #     ./gradlew test
-    #     echo "Testing process done."
-
-
-    # - name: Make HTTP GET request with curl - to esm, for deployment
-    #   run: |
-    #       echo 'entered depeloy step' 
-    #       BASE_URL="https://5045-86-127-179-145.ngrok-free.app/deploy"
-    #       PARAMS="?vmType=$vmType&repoUrl=https://github.com/$GITHUB_REPOSITORY.git&lastCommitHash=$GITHUB_SHA"
-
-    #       echo 'right before curl'
-    #       RESPONSE=$(curl -s -o response.json -w "%{http_code}" "${BASE_URL}${PARAMS}")
-    #       echo 'right after curl'
-
-    #       if [[ ${RESPONSE} -ge 400 ]]; then
-    #         echo "HTTP error occurred: ${RESPONSE}"
-    #         cat response.json
-    #         exit 1  # Exit with a non-zero status to fail the CI/CD pipeline
-    #       fi
-
-    #       echo "Success: ${RESPONSE}"
+          echo "Success: ${RESPONSE}"
